[package]
name = "skac"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
skald-compiler = { path = "../skald-compiler" }

[lints]
workspace = true

[[test]]
name = "golden"
path = "../../tests/golden/runner.rs"
harness = false

[[test]]
name = "golden-expectations"
path = "../../tests/golden/native_expectations_tests.rs"
