//! Native assembly fixtures for the standard-I/O backend behavior tests.

pub(super) fn read_failure_probe(read_result: i64, close_result: i64) -> String {
    format!(
        concat!(
            "\n.text\n",
            ".globl ska_rt_io_standard_handle\n",
            "ska_rt_io_standard_handle:\n",
            "    mov rax, rdi\n",
            "    ret\n",
            ".globl ska_rt_io_open\n",
            "ska_rt_io_open:\n",
            "    mov rax, 10\n",
            "    ret\n",
            ".globl ska_rt_io_read\n",
            "ska_rt_io_read:\n",
            "    mov rax, {read_result}\n",
            "    ret\n",
            ".globl ska_rt_io_write\n",
            "ska_rt_io_write:\n",
            "    mov rax, rdx\n",
            "    ret\n",
            ".globl ska_rt_io_close\n",
            "ska_rt_io_close:\n",
            "    mov rax, {close_result}\n",
            "    ret\n",
            ".globl ska_rt_alloc\n",
            "ska_rt_alloc:\n",
            "    jmp malloc@PLT\n",
            ".globl ska_rt_free\n",
            "ska_rt_free:\n",
            "    jmp free@PLT\n",
        ),
        read_result = read_result,
        close_result = close_result,
    )
}

pub(super) fn binary_read_probe() -> &'static str {
    concat!(
        "\n.bss\n",
        ".p2align 3\n",
        ".Lread_stdin_count: .quad 0\n",
        ".Lread_file_count: .quad 0\n",
        ".Lread_stdout_seen: .quad 0\n",
        ".Lread_stderr_seen: .quad 0\n",
        ".Lread_close_seen: .quad 0\n",
        "\n.text\n",
        ".globl ska_rt_io_standard_handle\n",
        "ska_rt_io_standard_handle:\n",
        "    mov rax, rdi\n",
        "    ret\n",
        ".globl ska_rt_io_open\n",
        "ska_rt_io_open:\n",
        "    mov rax, 10\n",
        "    ret\n",
        ".globl ska_rt_io_read\n",
        "ska_rt_io_read:\n",
        "    cmp rdx, 2\n",
        "    jb .Lread_failure\n",
        "    cmp rdi, 0\n",
        "    je .Lread_from_stdin\n",
        "    cmp rdi, 10\n",
        "    jne .Lread_failure\n",
        "    lea r8, [rip + .Lread_file_count]\n",
        "    mov r9d, 0x00008101\n",
        "    mov r10d, 0x000000fe\n",
        "    jmp .Lread_chunk\n",
        ".Lread_from_stdin:\n",
        "    lea r8, [rip + .Lread_stdin_count]\n",
        "    mov r9d, 0x00008000\n",
        "    mov r10d, 0x00000aff\n",
        ".Lread_chunk:\n",
        "    mov rcx, qword ptr [r8]\n",
        "    cmp rcx, 2\n",
        "    je .Lread_eof\n",
        "    ja .Lread_failure\n",
        "    mov eax, r9d\n",
        "    test rcx, rcx\n",
        "    cmovne eax, r10d\n",
        "    mov word ptr [rsi], ax\n",
        "    add qword ptr [r8], 1\n",
        "    mov rax, 2\n",
        "    ret\n",
        ".Lread_eof:\n",
        "    xor eax, eax\n",
        "    ret\n",
        ".globl ska_rt_io_write\n",
        "ska_rt_io_write:\n",
        "    cmp rdx, 4\n",
        "    jne .Lread_failure\n",
        "    cmp rdi, 1\n",
        "    je .Lread_write_stdout\n",
        "    cmp rdi, 2\n",
        "    jne .Lread_failure\n",
        "    cmp dword ptr [rsi], 0x00fe8101\n",
        "    jne .Lread_failure\n",
        "    mov qword ptr [rip + .Lread_stderr_seen], 1\n",
        "    mov rax, 4\n",
        "    ret\n",
        ".Lread_write_stdout:\n",
        "    cmp dword ptr [rsi], 0x0aff8000\n",
        "    jne .Lread_failure\n",
        "    mov qword ptr [rip + .Lread_stdout_seen], 1\n",
        "    mov rax, 4\n",
        "    ret\n",
        ".globl ska_rt_io_close\n",
        "ska_rt_io_close:\n",
        "    cmp rdi, 10\n",
        "    jne .Lread_failure\n",
        "    cmp qword ptr [rip + .Lread_file_count], 2\n",
        "    jne .Lread_failure\n",
        "    mov qword ptr [rip + .Lread_close_seen], 1\n",
        "    xor eax, eax\n",
        "    ret\n",
        ".Lread_failure:\n",
        "    ud2\n",
        ".globl validate\n",
        "validate:\n",
        "    cmp qword ptr [rip + .Lread_stdin_count], 2\n",
        "    jne .Lread_invalid\n",
        "    cmp qword ptr [rip + .Lread_stdout_seen], 1\n",
        "    jne .Lread_invalid\n",
        "    cmp qword ptr [rip + .Lread_stderr_seen], 1\n",
        "    jne .Lread_invalid\n",
        "    cmp qword ptr [rip + .Lread_close_seen], 1\n",
        "    jne .Lread_invalid\n",
        "    xor eax, eax\n",
        "    ret\n",
        ".Lread_invalid:\n",
        "    mov rax, 1\n",
        "    ret\n",
        ".globl ska_rt_alloc\n",
        "ska_rt_alloc:\n",
        "    jmp malloc@PLT\n",
        ".globl ska_rt_free\n",
        "ska_rt_free:\n",
        "    jmp free@PLT\n",
    )
}

pub(super) fn unused_read_probe() -> &'static str {
    concat!(
        "\n.text\n",
        ".globl ska_rt_io_open\n",
        "ska_rt_io_open:\n",
        "    mov rax, -1\n",
        "    ret\n",
        ".globl ska_rt_io_read\n",
        "ska_rt_io_read:\n",
        "    mov rax, -1\n",
        "    ret\n",
        ".globl ska_rt_io_close\n",
        "ska_rt_io_close:\n",
        "    mov rax, -1\n",
        "    ret\n",
    )
}

pub(super) fn invalid_write_probe(result: i64) -> String {
    format!(
        concat!(
            "\n.text\n",
            ".globl ska_rt_io_standard_handle\n",
            ".type ska_rt_io_standard_handle, @function\n",
            "ska_rt_io_standard_handle:\n",
            "    mov rax, rdi\n",
            "    ret\n",
            ".size ska_rt_io_standard_handle, .-ska_rt_io_standard_handle\n",
            ".globl ska_rt_io_write\n",
            ".type ska_rt_io_write, @function\n",
            "ska_rt_io_write:\n",
            "    mov rax, {result}\n",
            "    ret\n",
            ".size ska_rt_io_write, .-ska_rt_io_write\n",
            ".globl ska_rt_alloc\n",
            ".type ska_rt_alloc, @function\n",
            "ska_rt_alloc:\n",
            "    jmp malloc@PLT\n",
            ".size ska_rt_alloc, .-ska_rt_alloc\n",
            ".globl ska_rt_free\n",
            ".type ska_rt_free, @function\n",
            "ska_rt_free:\n",
            "    jmp free@PLT\n",
            ".size ska_rt_free, .-ska_rt_free\n",
        ),
        result = result,
    )
}

pub(super) fn partial_binary_write_probe() -> &'static str {
    concat!(
        "\n.section .rodata\n",
        ".Lio_expected: .byte 0, 128, 255, 10\n",
        "\n.bss\n",
        ".p2align 3\n",
        ".Lio_stdout_count: .quad 0\n",
        ".Lio_stderr_count: .quad 0\n",
        "\n.text\n",
        ".globl ska_rt_io_standard_handle\n",
        ".type ska_rt_io_standard_handle, @function\n",
        "ska_rt_io_standard_handle:\n",
        "    mov rax, rdi\n",
        "    ret\n",
        ".size ska_rt_io_standard_handle, .-ska_rt_io_standard_handle\n",
        ".globl ska_rt_io_write\n",
        ".type ska_rt_io_write, @function\n",
        "ska_rt_io_write:\n",
        "    cmp rdi, 1\n",
        "    je .Lio_write_stdout\n",
        "    cmp rdi, 2\n",
        "    jne .Lio_write_failure\n",
        "    lea r9, [rip + .Lio_stderr_count]\n",
        "    jmp .Lio_write_check\n",
        ".Lio_write_stdout:\n",
        "    lea r9, [rip + .Lio_stdout_count]\n",
        ".Lio_write_check:\n",
        "    mov rcx, qword ptr [r9]\n",
        "    cmp rcx, 4\n",
        "    jae .Lio_write_failure\n",
        "    mov rax, 4\n",
        "    sub rax, rcx\n",
        "    cmp rdx, rax\n",
        "    jne .Lio_write_failure\n",
        "    lea r8, [rip + .Lio_expected]\n",
        "    movzx eax, byte ptr [r8 + rcx]\n",
        "    cmp byte ptr [rsi], al\n",
        "    jne .Lio_write_failure\n",
        "    add qword ptr [r9], 1\n",
        "    mov rax, 1\n",
        "    ret\n",
        ".Lio_write_failure:\n",
        "    ud2\n",
        ".size ska_rt_io_write, .-ska_rt_io_write\n",
        ".globl validate\n",
        ".type validate, @function\n",
        "validate:\n",
        "    cmp qword ptr [rip + .Lio_stdout_count], 4\n",
        "    jne .Lio_validate_failure\n",
        "    cmp qword ptr [rip + .Lio_stderr_count], 4\n",
        "    jne .Lio_validate_failure\n",
        "    mov rax, 0\n",
        "    ret\n",
        ".Lio_validate_failure:\n",
        "    mov rax, 1\n",
        "    ret\n",
        ".size validate, .-validate\n",
        ".globl ska_rt_alloc\n",
        ".type ska_rt_alloc, @function\n",
        "ska_rt_alloc:\n",
        "    jmp malloc@PLT\n",
        ".size ska_rt_alloc, .-ska_rt_alloc\n",
        ".globl ska_rt_free\n",
        ".type ska_rt_free, @function\n",
        "ska_rt_free:\n",
        "    jmp free@PLT\n",
        ".size ska_rt_free, .-ska_rt_free\n",
    )
}

pub(super) fn closed_descriptor_write_probe() -> &'static str {
    concat!(
        "\n.text\n",
        ".globl ska_rt_io_standard_handle\n",
        ".type ska_rt_io_standard_handle, @function\n",
        "ska_rt_io_standard_handle:\n",
        "    mov rax, rdi\n",
        "    ret\n",
        ".size ska_rt_io_standard_handle, .-ska_rt_io_standard_handle\n",
        ".globl ska_rt_io_write\n",
        ".type ska_rt_io_write, @function\n",
        "ska_rt_io_write:\n",
        "    mov r8, rdi\n",
        "    mov r9, rsi\n",
        "    mov r10, rdx\n",
        "    mov rax, 3\n",
        "    syscall\n",
        "    mov rax, 1\n",
        "    mov rdi, r8\n",
        "    mov rsi, r9\n",
        "    mov rdx, r10\n",
        "    syscall\n",
        "    ret\n",
        ".size ska_rt_io_write, .-ska_rt_io_write\n",
        ".globl ska_rt_alloc\n",
        ".type ska_rt_alloc, @function\n",
        "ska_rt_alloc:\n",
        "    jmp malloc@PLT\n",
        ".size ska_rt_alloc, .-ska_rt_alloc\n",
        ".globl ska_rt_free\n",
        ".type ska_rt_free, @function\n",
        "ska_rt_free:\n",
        "    jmp free@PLT\n",
        ".size ska_rt_free, .-ska_rt_free\n",
    )
}
