//! Type checking and construction of typed HIR.

mod arrays;
mod capabilities;
mod containment;
mod expression;
mod function;
mod literal;
mod optional;
mod program;
mod shared;

pub use arrays::{
    ARRAY_CAPABILITY_UNAVAILABLE, ARRAY_LENGTH_OUT_OF_RANGE, ARRAY_PROJECTION_REQUIRES_ARRAY,
    INVALID_ARRAY_ELEMENT,
};
pub use containment::RECURSIVE_INLINE_CONTAINMENT;
pub use program::{
    type_check, TypeCheckOutput, AMBIGUOUS_INITIALIZER, COPY_OPERATION_UNAVAILABLE,
    F64_LITERAL_OUT_OF_RANGE, FIELD_INITIALIZATION, IMPLICIT_SHARED_DEREFERENCE,
    INSUFFICIENT_ALIAS_ACCESS, INTEGER_LITERAL_OUT_OF_RANGE, INVALID_ALIAS_ARGUMENT,
    INVALID_ALIAS_PARAMETER, INVALID_CALL_STATEMENT, INVALID_CONSTRUCTION,
    INVALID_COPY_CONSTRUCTION, INVALID_ENTRY_POINT, INVALID_EXTERNAL_DECLARATION,
    INVALID_INITIALIZER_BODY, INVALID_INTERFACE_CONFORMANCE, INVALID_INTERFACE_REQUIREMENT,
    INVALID_OBJECT_CONTEXT, INVALID_OBJECT_DECLARATION, INVALID_OVERRIDE_SIGNATURE, INVALID_RETURN,
    INVALID_SHARED_CONVERSION, INVALID_STATIC_FIELD_TYPE, INVALID_TYPE_TEST, MISSING_ENTRY_POINT,
    MISSING_RETURN, NO_MATCHING_INITIALIZER, PANIC_REQUIRES_CALL_STATEMENT,
    PRIVATE_INITIALIZER_ACCESS, READ_ONLY_RECEIVER, STATIC_FIELD_USE_UNAVAILABLE,
    STATIC_STORAGE_NOT_LOWERED, TYPE_MISMATCH, U64_LITERAL_OUT_OF_RANGE, U8_LITERAL_OUT_OF_RANGE,
    WRONG_ARGUMENT_COUNT,
};

#[cfg(test)]
mod tests;
