//! Type checking and construction of typed HIR.

mod expression;
mod function;
mod literal;
mod program;

pub use program::{
    type_check, TypeCheckOutput, ALIAS_PARAMETER_NOT_TYPE_CHECKED, F64_LITERAL_OUT_OF_RANGE,
    FIELD_INITIALIZATION, INTEGER_LITERAL_OUT_OF_RANGE, INVALID_CALL_STATEMENT,
    INVALID_CONSTRUCTION, INVALID_ENTRY_POINT, INVALID_EXTERNAL_DECLARATION,
    INVALID_INITIALIZER_BODY, INVALID_OBJECT_CONTEXT, INVALID_OBJECT_DECLARATION, INVALID_RETURN,
    MISSING_ENTRY_POINT, MISSING_RETURN, READ_ONLY_RECEIVER, TYPE_MISMATCH,
    U64_LITERAL_OUT_OF_RANGE, U8_LITERAL_OUT_OF_RANGE, WRONG_ARGUMENT_COUNT,
};

#[cfg(test)]
mod tests;
