//! Type checking and construction of typed HIR.

mod arrays;
mod capabilities;
mod categories;
mod containment;
mod conversion;
mod diagnostic_codes;
mod expression;
mod function;
mod literal;
mod optional;
mod optional_box_types;
mod optional_types;
mod optional_validation;
mod program;
mod shared;
mod shared_compatibility;
mod stored_value;

pub use arrays::{
    ARRAY_CAPABILITY_UNAVAILABLE, ARRAY_LENGTH_OUT_OF_RANGE, ARRAY_PROJECTION_REQUIRES_ARRAY,
    INVALID_ARRAY_ELEMENT,
};
pub use containment::RECURSIVE_INLINE_CONTAINMENT;
pub use diagnostic_codes::{
    AMBIGUOUS_INITIALIZER, AMBIGUOUS_OPERATOR_APPLICATION, COPY_OPERATION_UNAVAILABLE,
    F64_LITERAL_OUT_OF_RANGE, FIELD_INITIALIZATION, FINAL_FIELD_REPLACEMENT,
    FINAL_STATIC_INITIALIZER_REQUIRED, FINAL_STATIC_REPLACEMENT, GENERAL_ITERATION_UNSUPPORTED,
    IMPLICIT_SHARED_DEREFERENCE, INCOMPATIBLE_OPERATOR_RHS, INSUFFICIENT_ALIAS_ACCESS,
    INTEGER_LITERAL_OUT_OF_RANGE, INVALID_ALIAS_ARGUMENT, INVALID_ALIAS_PARAMETER,
    INVALID_CALL_STATEMENT, INVALID_CONSTRUCTION, INVALID_COPY_CONSTRUCTION, INVALID_ENTRY_POINT,
    INVALID_EXTERNAL_DECLARATION, INVALID_INITIALIZER_BODY, INVALID_INTERFACE_CONFORMANCE,
    INVALID_INTERFACE_REQUIREMENT, INVALID_OBJECT_CAST, INVALID_OBJECT_CONTEXT,
    INVALID_OBJECT_DECLARATION, INVALID_OPERATOR_SELECTION, INVALID_OVERRIDE_SIGNATURE,
    INVALID_RESOLVED_F64_LITERAL, INVALID_RESOLVED_RANGE_SOURCE, INVALID_RETURN,
    INVALID_SHARED_CONVERSION, INVALID_STATIC_FIELD_TYPE, INVALID_TYPE_TEST, MISSING_ENTRY_POINT,
    MISSING_RETURN, NO_MATCHING_INITIALIZER, PANIC_REQUIRES_CALL_STATEMENT,
    PRIVATE_INITIALIZER_ACCESS, READ_ONLY_RECEIVER, TYPE_MISMATCH, U64_LITERAL_OUT_OF_RANGE,
    U8_LITERAL_OUT_OF_RANGE, UNSUPPORTED_OPERATOR_APPLICATION, WRONG_ARGUMENT_COUNT,
};
pub use optional_validation::INVALID_OPTIONAL_TYPE;
pub use program::{type_check, TypeCheckOutput};

#[cfg(test)]
mod tests;
